title: "Fire9"
url: "http://fire9.org"
author: "Fire9"
email: "fire9@me.com"
description: "The personal blog of Fire9"

auto: false
source: .
paginate: 5
paginate_files:
 - index.html

permalink: /:year/:month/:title

markdown: rdiscount
pygments: true

exclude:
  - README.markdown
  - _drafts
